name: Publish CocoaPods Release

on:
  release:
    types:
      - published

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  publish-podspec:
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ^15.2
      - uses: actions/checkout@v4
      - name: Generate Podspec
        env:
          EXPECTED_VERSION: ${{ github.event.release.tag_name }}
        run: ./Scripts/generate-podspec.sh "${EXPECTED_VERSION}"
      - name: Publish Podspec
        run: pod repo push vg-specs CocoaLumberjack.podspec --verbose --allow-warnings --skip-import-validation
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
